spring:
  kafka:
    bootstrap-servers: kafka:9093
    properties:
      security.protocol: SSL
      ssl.truststore.location: /app/certs/kafka.truststore.jks
      ssl.truststore.password: confluent
      ssl.keystore.location: /app/certs/kafka.keystore.jks
      ssl.keystore.password: confluent
      ssl.key.password: confluent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: https://schema-registry:8081
server:
  port: 8083