spring:
  kafka:
    bootstrap-servers: kafka:9093,kafka-2:9093,kafka-3:9093
    properties:
      security.protocol: SSL
      ssl.truststore.location: /app/certs/kafka.truststore.jks
      ssl.truststore.password: confluent
      ssl.keystore.location: /app/certs/kafka.keystore.jks
      ssl.keystore.password: confluent
      ssl.key.password: confluent
      schema.registry.url: https://schema-registry:8081
      schema.registry.ssl.truststore.location: /app/certs/kafka.truststore.jks
      schema.registry.ssl.truststore.password: confluent
      schema.registry.ssl.truststore.type: JKS
    consumer:
      group-id: audit-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: https://schema-registry:8081
        specific.avro.reader: true
        use.latest.version: true
        auto.register.schemas: false
  datasource:
    url: jdbc:postgresql://postgres:5432/audit_db
    username: audit
    password: audit
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8085
debug: true