spring:
  kafka:
    bootstrap-servers: localhost:9095
    properties:
      security.protocol: SSL
      ssl.truststore.location: certs/kafka.truststore.jks
      ssl.truststore.password: confluent
      ssl.keystore.location: certs/kafka.keystore.p12
      ssl.keystore.password: confluent
      ssl.key.password: confluent
    consumer:
      group-id: audit-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
  datasource:
    url: jdbc:postgresql://localhost:5435/audit_db
    username: audit
    password: audit
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8085
debug: true