KafkaServer {
  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
  clientId="kafka-broker"
  clientSecret="kafka-broker-secret"
  oauth.token.endpoint.uri="https://keycloak:8443/realms/banking-realm/protocol/openid-connect/token";
};
