KafkaServer {
  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
  clientId="kafka-broker"
  scope="email"
  serviceName="kafka"
  unsecuredLoginStringClaim_sub="preferred_username";
};