KafkaServer {
  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
  clientId="kafka-broker"
  clientSecret="2cPOCZiL0mTy0pZimASWjRXfFUWRcSoA"
  scope="email"
  unsecuredLoginStringClaim_sub="preferred_username";
};