KafkaClient {
   org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
   oauth.client.id="notification-service"
   oauth.client.secret="notification-secret"
   oauth.token.endpoint.uri="https://keycloak:8443/realms/banking-realm/protocol/openid-connect/token"
   oauth.scope="kafka-broker";
};